# Generated by Django 3.2.25 on 2024-09-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20240919_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
