# Generated by Django 4.1.7 on 2024-09-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='generated_lyrics',
        ),
        migrations.AddField(
            model_name='lyrics',
            name='chorus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='verse1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='verse2',
            field=models.TextField(blank=True),
        ),
    ]
