# Generated by Django 4.1.7 on 2024-09-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_lyrics_generated_lyrics_lyrics_chorus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='bridge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='outro',
            field=models.TextField(blank=True),
        ),
    ]
