# Generated by Django 4.1.7 on 2024-09-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
