# Generated by Django 4.1.7 on 2024-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_category_music_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='category',
            field=models.CharField(choices=[('pop', 'Pop'), ('hip-hop', 'Hip-Hop'), ('rock', 'Rock'), ('jazz', 'Jazz')], max_length=50),
        ),
    ]
