# Generated by Django 4.1.7 on 2024-09-30 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_music_artist_alter_music_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(default='path/to/placeholder.mp3', upload_to='music/'),
        ),
    ]
